name: tmp

on:
  push:
  workflow_dispatch:
jobs:
  tkn:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          script: "console.log(JSON.stringify(JSON.parse(Buffer.from(process.env['ACTIONS_RUNTIME_TOKEN'].split('.')[1], 'base64').toString('utf8')), null, 2))"
