name: tmp

on:
  workflow_dispatch:
jobs:
  tkn:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          script: "console.log(JSON.stringify(JSON.parse(atob(process.env['ACTIONS_RUNTIME_TOKEN'].split('.')[1])), null, 2))"
